version: '3.8'

services:
  db:
    image: mongo:latest
    # 意図せず停止した場合でも常に自動で再起動するよう設定
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: image_uploader_db
      TZ: Asia/Tokyo
    ports:
      - "27017:27017"
    volumes:
      # コンテナのライフサイクルに依存しないデータの永続化
      - mongo_data:/data/db

  app:
    build: .
    volumes:
      - ./app:/usr/src/app
      - ./images/upload:/images/upload
    environment:
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_HOST: db
      MONGO_PORT: "27017"
      MONGO_DB: image_uploader_db
      TZ: Asia/Tokyo
    # MongoDBの起動を待ってからアプリを起動
    depends_on:
      - db
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

volumes:
  mongo_data: